### ISSUE TITLE
kelunik/acme is still using amphp/amp v1, will it be upgraded to use v2?

### ISSUE THREAD

**Issue by vanoostrum** [kelunik/acme#24]
I'm having an issues with amphp/dns: DefaultResolver.php, 632 - "Undefined offset: 8". I suspect this is a bug in amphp/dns which might have been resolved in a newer version of amphp/dns, seeing that the class DefaultResolver doesn't exist anymore.

Furthermore, I don't see much recent activity on the kelunik/acme repo. Is there any intention of working towards a new version which will use amphp/amp 2.x?

**Comment by kelunik** [comment]
Could you report the bug in `amphp/dns` please?

And yes, there will be a version based on Amp v2, but there are a few things we need to solve first. One thing is making `amphp/process` 100% Windows compatible. Another thing is that I wanted to wait for Let's Encrypts ACME v2 endpoint.

**Comment by vanoostrum** [comment]
Ok I understand. Not sure if reporting the bug on amphp/dns makes sence because it's related to an older version an it may be difficult to reproduce.

**Comment by kelunik** [comment]
The latest Amp v1 version of `amphp/dns` is still supported until the end of the year.

**Comment by vanoostrum** [comment]
Ok I will see if I can reproduce the issue in a clear way and report the bug. Thanks!

**Comment by kelunik** [comment]
@vanoostrum Just open the issue either way. It's clearly a bug.
