### ISSUE TITLE
PHPDoc links doesn't work

### ISSUE THREAD

**Issue by prewk** [kelunik/acme#25]
Following links to https://blog.kelunik.com/docs/acme/classes/AcmeService.html#register etc gives 404.

**Comment by kelunik** [comment]
I guess the currently deployed version is out of date anyway. Will have to find the command I used for the generation of it.

**Comment by kelunik** [comment]
You can use https://docs.kelunik.com/kelunik/acme/v0.3.3 for now instead.

**Comment by prewk** [comment]
Thanks! (I can check the source as well, was more of a notice that it was broken)
