### ISSUE TITLE
Certificate Renewal only for 5-6 days

### ISSUE THREAD

**Issue by WallBB** [kelunik/acme#29]
I am using below command to renew certificate of one of my domain using lets encrypt service but after using the below command, I see that the certificate is renewed for only 5-6 days
php acme-client/bin/acme issue --domains example.com:www.example.com --path /home/peter/example:/home/peter/example --server letsencrypt

Is this expected or something is wrong in my command ?

**Comment by kelunik** [comment]
What do you mean by _"is renewed for only 5-6 days"_? Do you mean it's renewed every 5-6 days?

`acme issue` directly issues a new certificate and doesn't do any checks for existing certificates. You have to combine it with `acme check` or directly use `acme auto`.

**Comment by WallBB** [comment]
This can be closed now, the certificate is expiring in 5 days so I thought after renewal it is expiring again.
I believe the renewal happens once it expires ?

**Comment by kelunik** [comment]
A renewal doesn't happen automatically. You have to either invoke `acme issue` manually or `acme auto` in a regular interval with the certificate specified in the configuration.

**Comment by kelunik** [comment]
I just noticed that this has been reported on the wrong repository. New issues with the client should go to https://github.com/kelunik/acme-client please.
