### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ramonschriks** [kelunik/acme#35]
Hi, is it possible to create a new release whenever it is safe to use?
We are using a fork of your repo atm, and fetched it recently to be up-to-date with yours.

Basically, our fork is equal to yours now. But you don't have a release yet with this new ACME v2 changes.

**Comment by kelunik** [comment]
Hey @ramonschriks,

thanks for the reminder! Seems I've forgotten to tag a release here, there's a release for the client now at https://github.com/kelunik/acme-client/releases/tag/v1.0.0-beta.2, but I'm using the `-dev` version there.

I'll tag a release when I'm on the right computer with the signing key.

**Comment by kelunik** [comment]
I've tagged a release now: https://github.com/kelunik/acme/releases/tag/v1.0.0

Thanks! :partying_face:
