### ISSUE TITLE
Acme HTTP Errors

### ISSUE THREAD

**Issue by barryvdh** [kelunik/acme#4]
The Acme service can return certain error codes, as described here: https://letsencrypt.github.io/acme-spec/#rfc.section.5.4

Currently, HTTP errors will be thrown with the response body as plain text in the message.

It would be more useful to create a `AcmeHttpException` which can be constructed using the response object and provides an actual useful message?

> Invalid response code: 400 {"type":"urn:acme:error:badNonce","detail":"Unable to read/verify body :: JWS has invalid anti-replay nonce","status":400}

Could be:

> Invalid Acme HTTP Response: badNonce (code 400). Unable to read/verify body :: JWS has invalid anti-replay nonce.

**Comment by kelunik** [comment]
`BadCsrException`, `BadNonceException`, `ConnectException`, `DnssecException`, `MalformedRequestException`, `InternalServerException`, `TlsException`, `UnauthorizedException`, `UnknownHostException`.

I'm not happy with some of these names, do you have suggestions?

**Comment by kelunik** [comment]
Another alternative would be to return the `type` in `AcmeException::getCode`.

**Comment by staabm** [comment]
I agree that all of those errors should be represented by 1 class which then provides a method to further determine the underlying error

**Comment by kelunik** [comment]
I have improved the error messages, please review d3805a6d11944c9296641a435aa710bcaa646fdf.

**Comment by barryvdh** [comment]
What about doing the type/detail handling inside the exception?

You can change the Exception constructor when extending, for example to typehint a Response object. You can then apply the same logic in your Eception.
You could also create a static factory for your AcmeException, to create on from a Response.

```php
class AcmeException extends Exception {
    public function __construct($message, Response $response = null, Exception $previous = null)
    {
        parent::__construct($message, 0, $previous);

        if ($response) {
            $info = json_decode($response->getBody(), true);

            if ($info && isset($info['type'], $info['detail'])) {
                $this->code = $info['type'];
                $this->message .= ' ' . $info['detail'];
            }
        }

    }
}
```

https://3v4l.org/WgOnF

**Comment by kelunik** [comment]
Should the default error code be `internal`, `generic`, `general` or `unknown`?

**Comment by barryvdh** [comment]
Don't know, could just leave it 0, the Exception default.

**Comment by kelunik** [comment]
Can I close this?

**Comment by barryvdh** [comment]
Hmm, using a string as code might give unexpected results when stacking exceptions, see: https://github.com/Petertjuh360/da-letsencrypt/issues/40
Testcase: https://3v4l.org/ObN47
